#include "Testing/TMOPNavigationTestDirector.h"

#include "Actions/TMOPActionExecutorComponent.h"
#include "Agents/TMOPHistoricalAgent.h"
#include "Anchors/TMOPAnchorSubsystem.h"
#include "Anchors/TMOPHistoricalAnchor.h"
#include "Engine/GameInstance.h"
#include "Engine/World.h"
#include "Schedules/TMOPScheduleTypes.h"
#include "World/TMOPWorldSubsystem.h"

ATMOPNavigationTestDirector::ATMOPNavigationTestDirector()
{
    PrimaryActorTick.bCanEverTick = true;
    PrimaryActorTick.bStartWithTickEnabled = false;
}

void ATMOPNavigationTestDirector::BeginPlay()
{
    Super::BeginPlay();

    if (!bStartAutomatically)
    {
        return;
    }

    RemainingDelaySeconds = FMath::Max(0.0f, StartDelaySeconds);
    bAutomaticStartPending = true;

    if (RemainingDelaySeconds <= 0.0f)
    {
        bAutomaticStartPending = false;
        StartNavigationTest();
        return;
    }

    SetActorTickEnabled(true);
}

void ATMOPNavigationTestDirector::Tick(const float DeltaSeconds)
{
    Super::Tick(DeltaSeconds);

    if (!bAutomaticStartPending)
    {
        SetActorTickEnabled(false);
        return;
    }

    RemainingDelaySeconds -= DeltaSeconds;

    if (RemainingDelaySeconds <= 0.0f)
    {
        bAutomaticStartPending = false;
        SetActorTickEnabled(false);
        StartNavigationTest();
    }
}

bool ATMOPNavigationTestDirector::StartNavigationTest()
{
    UWorld* World = GetWorld();
    UGameInstance* GameInstance =
        World != nullptr ? World->GetGameInstance() : nullptr;

    if (GameInstance == nullptr)
    {
        OnNavigationTestStarted.Broadcast(false);
        return false;
    }

    UTMOPWorldSubsystem* WorldSubsystem =
        GameInstance->GetSubsystem<UTMOPWorldSubsystem>();

    UTMOPAnchorSubsystem* AnchorSubsystem =
        GameInstance->GetSubsystem<UTMOPAnchorSubsystem>();

    if (WorldSubsystem == nullptr || AnchorSubsystem == nullptr)
    {
        UE_LOG(
            LogTemp,
            Error,
            TEXT("TMOP navigation test failed: required subsystem missing."));
        OnNavigationTestStarted.Broadcast(false);
        return false;
    }

    AnchorSubsystem->DiscoverAnchorsInWorld();

    ATMOPHistoricalAgent* Agent =
        Cast<ATMOPHistoricalAgent>(
            WorldSubsystem->FindWorldObject(AgentId));

    ATMOPHistoricalAnchor* StartAnchor =
        AnchorSubsystem->FindAnchor(StartAnchorId);

    ATMOPHistoricalAnchor* EndAnchor =
        AnchorSubsystem->FindAnchor(EndAnchorId);

    if (!IsValid(Agent))
    {
        UE_LOG(
            LogTemp,
            Error,
            TEXT("TMOP navigation test failed: agent '%s' not found."),
            *AgentId.ToString());
        OnNavigationTestStarted.Broadcast(false);
        return false;
    }

    if (!IsValid(EndAnchor))
    {
        UE_LOG(
            LogTemp,
            Error,
            TEXT("TMOP navigation test failed: end anchor '%s' not found."),
            *EndAnchorId.ToString());
        OnNavigationTestStarted.Broadcast(false);
        return false;
    }

    if (bTeleportAgentToStart)
    {
        if (!IsValid(StartAnchor))
        {
            UE_LOG(
                LogTemp,
                Error,
                TEXT("TMOP navigation test failed: start anchor '%s' not found."),
                *StartAnchorId.ToString());
            OnNavigationTestStarted.Broadcast(false);
            return false;
        }

        Agent->SetActorLocationAndRotation(
            StartAnchor->GetAnchorLocation() +
                FVector(0.0f, 0.0f, StartHeightOffset),
            StartAnchor->GetAnchorRotation(),
            false,
            nullptr,
            ETeleportType::TeleportPhysics);
    }

    if (Agent->ActionExecutor == nullptr)
    {
        UE_LOG(
            LogTemp,
            Error,
            TEXT("TMOP navigation test failed: agent has no ActionExecutor."));
        OnNavigationTestStarted.Broadcast(false);
        return false;
    }

    Agent->MovementPolicy = MovementPolicy;
    Agent->SetActivityState(MovementActivity);

    FTMOPScheduleEntry TestEntry;
    TestEntry.EntryId = TEXT("TEST_MOVE_TO_END");
    TestEntry.ActionType = ETMOPScheduleActionType::MoveToAnchor;
    TestEntry.TargetAnchorId = EndAnchorId;
    TestEntry.ActivityState = MovementActivity;
    TestEntry.Confidence =
        ETMOPHistoricalConfidence::FictionalGameplay;
    TestEntry.Notes =
        TEXT("Generated by TMOPNavigationTestDirector.");

    const bool bStarted =
        Agent->ActionExecutor->ExecuteScheduleEntry(TestEntry);

    UE_LOG(
        LogTemp,
        Log,
        TEXT("TMOP navigation test start result: %s"),
        bStarted ? TEXT("success") : TEXT("failed"));

    OnNavigationTestStarted.Broadcast(bStarted);
    return bStarted;
}
